blog/urls.py
from django.urls import path 

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailsView.as_view(), name='post_details'),
    path('comment/<int:post_id>/', views.BlogPostCommentView.as_view(), name='comment_create'),
    path('categories/<slug:slug>/', views.categories_post_list, name='categories_post_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path 

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('contact_us/', views.ContactUsView.as_view(), name='contact_us'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth import get_user_model

from ckeditor.fields import RichTextField


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, related_name="children", verbose_name=_('category_parent'))
    
    title = models.CharField(_('title'), max_length=200)
    
    slug = models.SlugField(_('slug'), unique=True, max_length=250)
    
    status = models.BooleanField(_('status'), default=True)

    position = models.IntegerField(_('position'))

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'
        ordering = ('parent__id', 'position')
    
    def __str__(self):
        return self.title

    object = CategoryManager()


# My manager class
class PostManager(models.Manager):
    def published(self):
        return self.filter(status = 'pu').order_by('published')


class BlogPost(models.Model):
    
    """
    This is the class for creating a new blog post.
    """
    
    STATUS_CHOICES = [
        ('dr', _('draft')),
        ('pu', _('published')),
    ]
    
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='posts', verbose_name=_('author'))
    
    title = models.CharField(_('title'), max_length=250)
    
    slug = models.SlugField(_('slug'), unique=True, max_length=250)

    category = models.ManyToManyField(Category, verbose_name=_('Category'), related_name="categories")
    
    content = RichTextField(_('content')) 
    
    image = models.ImageField(_('image'), upload_to='media')
    
    published = models.DateTimeField(_('published'), default = timezone.now())
    
    datetime_creation = models.DateTimeField(_('datetime_creation'), auto_now_add = True)
    
    datetime_modified = models.DateTimeField(_('datetime_modified'), auto_now = True)
    
    is_active = models.BooleanField(_('active'), default = True)
    
    status = models.CharField(_('status'), choices=STATUS_CHOICES, max_length=10)
    
    class Meta:
        verbose_name = _('Blog Post')
        verbose_name_plural = _('Blog Posts')
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_details", args=[ self.pk ])

    def categories_Status_true(self):
        return self.category.filter(status=True)
    
    
    object = PostManager()
    
class BlogPostComment(models.Model):
    
    """
    This class is for creating a comment on a blog post.
    """
    
    STARS_CHOICES = [
        ('1', _("worst")),
        ('2', _("bad")),
        ('3', _("normal")),
        ('4', _("good")),
        ('5', _("perfect")),
    ]
    
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_('User'), related_name='comments')
    
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, verbose_name=_('BlogPost'), related_name='comments')
    
    description = models.TextField(_('Description'))
    
    stars = models.CharField(_('Stars'), max_length=10, choices=STARS_CHOICES)
    
    is_active = models.BooleanField(_('is_active'), default=True)

    published = models.DateTimeField(_('published'), default = timezone.now())
    
    datetime_creation = models.DateTimeField(_('datetime_creation'), auto_now_add = True)
    
    datetime_modified = models.DateTimeField(_('datetime_modified'), auto_now = True)

    class Meta:
        verbose_name = _('Blog Post Comment')
        verbose_name_plural = _('Blog Post Comments')
    

    def __str__(self):
        return f'user:{self.user} / post:{self.post}'
    
    
    def get_absolute_url(self):
        return reverse('blog:post_details', args=[self.post.id])
    

utils/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm , UserChangeForm


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        fields = ['username', 'email']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        fields = ['username', 'email']
        

blog/forms.py
from django import forms

from .models import BlogPostComment

class BlogPostCommentForm(forms.ModelForm):
    class Meta:     
        model = BlogPostComment
        
        fields = ['description', 'stars']

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.urls import reverse_lazy

from .models import BlogPost, BlogPostComment, Category
from .forms import BlogPostCommentForm

class PostListView(generic.ListView):
    # model = BlogPost
    queryset = BlogPost.objects.published()
    
    template_name = 'blog/post_list.html'
    
    context_object_name = 'posts'


class PostDetailsView(generic.DetailView):
    model = BlogPost
    
    template_name = 'blog/post_details.html'
    
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['comment_form'] = BlogPostCommentForm
        
        return context
    

class BlogPostCommentView(generic.CreateView):
    model = BlogPostComment
    
    form_class = BlogPostCommentForm
    
    # def get_success_url(self) -> str:
    #     return reverse('blog:post_list')
    
            
    def form_valid(self, form):
        comment = form.save(commit=False)
        
        comment.user = self.request.user
        
        post_id = int(self.kwargs['post_id'])
        
        post = get_object_or_404(BlogPost, id=post_id)
        
        comment.post = post
                
        return super().form_valid(form)


# class CategoriesPostListView(generic.ListView):
    
#     model = Category
    
#     template_name = "blog/categories_post_list.html"
    
#     context_object_name = "category_posts"

def categories_post_list(request, slug):
    context = {
        "categories_posts": get_object_or_404(Category, slug=slug, status=True) 
    }
    
    return render(request, "blog/categories_post_list.html", context)

pages/views.py
from django.shortcuts import render
from django.views import generic

from blog.models import BlogPost

class HomeView(generic.ListView):
    model = BlogPost
    
    template_name = 'home.html'

    context_object_name = 'posts'


class ContactUsView(generic.TemplateView):
    template_name = 'pages/contact_us.html'

utils/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/categories_post_list.html
{% extends '_base.html' %}

<!-- Django filters -->
{% load i18n %}

<!-- Third party filters -->
{% load jalali_tags %}

<!-- My filters -->
{% load persian_translate_tags %}


{% block title %}

    {% trans 'post list'%}

{% endblock %}

{% block body %}

  <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                {% for post in categories_posts.categories.published %}
                  <div class="col-lg-6">
                    <div class="blog-post">
                      <div class="blog-thumb">
                        <a href="{{ post.get_absolute_url }}">
                          <img src="{{ post.image.url }}" alt="">
                        </a>
                      </div>
                      <div class="down-content">
                        <a href="{{ post.get_absolute_url }}">
                          <span>{{ post.title }}</span>
                        </a>
                        <ul class="post-info">
                          <li><a href="#">{{ post.author }}</a></li>
                          <li><a href="#">{{ post.published|to_jalali:'%Y %B %d'|number }}</a></li>
                          <li><a href="#">{{ post.comments.all|length }} {% trans "Comments" %}</a></li>
                        </ul>
                        <p>{{ post.content|truncatewords:10|safe }}</p>
                        <div class="post-options">
                          <div class="row">
                            <div class="col-6">
                              <ul class="post-tags">
                                <li><i class="fa fa-tags"></i></li>
                                {% for category in post.categories_Status_true.all %}
                                  <li><a href="#">{{ category.title }}</a>,</li>
                                {% endfor %}
                              </ul>
                            </div>
                            <div class="col-6">
                              <ul class="post-share">
                                <li><i class="fa fa-share-alt"></i></li>
                                <li><a href="#">Facebook</a>,</li>
                                <li><a href="#"> Twitter</a></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
                <div class="col-12">
                  <nav aria-label="Page navigation example">
                      <ul class="pagination justify-content-center mt_3">
                          {% if page_obj.has_previous %}
                              <li class="page-item">
                                  <a class="page-link" href="?page={{ page_obj.previous_page_number}}">{% trans "Previous"%}</a>
                              </li>
                          {% endif %}
                          <li class="page-item">
                              <a class="page-link" href="#">1</a>
                          </li>
                          {% if page_obj.has_next %}
                              <li class="page-item">
                                  <a class="page-link" href="?page={{ page_obj.next_page_number}}">{% trans "Next"%}</a>
                              </li>
                          {% endif %}
                      </ul>
                  </nav>   
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </section>
  
{% endblock %}

blog/templates/blog/post_details.html
{% extends '_base.html' %}

<!-- Django filters -->
{% load i18n %}

<!-- Third party filters -->
{% load jalali_tags %}

<!-- My filters -->
{% load persian_translate_tags %}

{% block title %}

    {% trans 'post details'%}

{% endblock %}

{% block body %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="text-content">
                  <h4>Post Details</h4>
                  <h2>Single blog post</h2>
                </div>
              </div>
            </div>
          </div>
        </section>
    </div>
      
    <!-- Banner Ends Here --> 
  
    <section class="blog-posts grid-system">
        <div class="container">
          <div class="row">
            <div class="col-lg-8">
              <div class="all-blog-posts">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="blog-post">
                      <div class="blog-thumb">
                        <img src="{{ post.image.url }}" alt="">
                      </div>
                      <div class="down-content">
                        <span>{{ post.title }}</span>
                        <ul class="post-info">
                          <li><a href="#">{{ post.author }}</a></li>
                          <li><a href="#"> {{ post.published|to_jalali:'%Y %B %d'|number }}</a></li>
                          <li><a href="#">{{ post.comments.all|length }} {% trans "Comments" %}</a></li>
                        </ul>
                        <p>
                            {{ post.content|safe }}
                        </p>
                        <div class="post-options">
                          <div class="row">
                            <div class="col-6">
                              <ul class="post-tags">
                                <li><i class="fa fa-tags"></i></li>
                                {% for category in post.categories_Status_true.all %}
                                  <li><a href="#">{{ category.title }}</a>,</li>
                                {% endfor %}                              
                              </ul>
                            </div>
                            <div class="col-6">
                              <ul class="post-share">
                                <li><i class="fa fa-share-alt"></i></li>
                                <li><a href="#">Facebook</a>,</li>
                                <li><a href="#"> Twitter</a></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item comments">
                        <div class="sidebar-heading">
                          <h2>{{ post.comments.all|length }} {% trans "Comments" %}</h2>
                        </div>
                        {% for comment in post.comments.all %}
                          <div class="content">
                            <ul>
                              <li>
                                <div class="author-thumb">
                                  <img src="assets/images/comment-author-01.jpg" alt="">
                                </div>
                                <div class="right-content">
                                  <h4>{{ comment.user.username }}<span>{{ comment.published|to_jalali:'%Y %B %d'|number }}</span></h4>
                                  <p>
                                    {{ comment.description|linebreaks }}
                                  </p>
                                </div>
                              </li>
                            </ul>
                          </div>
                        {% endfor %}
                      </div>
                    </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item submit-comment">
                      <div class="sidebar-heading">
                        <h2>{% trans "Your comment" %}</h2>
                      </div>
                      <div class="content">
                        <form id="comment" action="{% url 'blog:comment_create' post.id %}" method="POST">
                          {% csrf_token %}
                          <div class="row">
                            <div class="col-lg-12">
                              <fieldset>
                                <textarea name="description" rows="6" id="description" placeholder="{% trans "Type your comment" %}" required=""></textarea>
                              </fieldset>
                            </div>
                            <div class="col-md-6 col-sm-12">
                              <fieldset>
                                <input name="stars" type="text" id="stars" class="rating"  placeholder="{% trans "Your stars form 1 to 5"%}" required="">
                              </fieldset>
                            </div>
                            <div class="col-lg-12">
                              <fieldset>
                                <button type="submit" class="main-button">{% trans "Submit" %}</button>
                              </fieldset>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="sidebar">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="sidebar-item search">
                      <form id="search_form" name="gs" method="GET" action="#">
                        <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
                      </form>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item recent-posts">
                      <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="post-details.html">
                            <h5>Vestibulum id turpis porttitor sapien facilisis scelerisque</h5>
                            <span>May 31, 2020</span>
                          </a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item categories">
                      <div class="sidebar-heading">
                        <h2>Categories</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="#">- Nature Lifestyle</a></li>
                          <li><a href="#">- Awesome Layouts</a></li>
                          <li><a href="#">- Creative Ideas</a></li>
                          <li><a href="#">- Responsive Templates</a></li>
                          <li><a href="#">- HTML5 / CSS3 Templates</a></li>
                          <li><a href="#">- Creative &amp; Unique</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="sidebar-item tags">
                      <div class="sidebar-heading">
                        <h2>Tag Clouds</h2>
                      </div>
                      <div class="content">
                        <ul>
                          <li><a href="#">Lifestyle</a></li>
                          <li><a href="#">Creative</a></li>
                          <li><a href="#">HTML5</a></li>
                          <li><a href="#">Inspiration</a></li>
                          <li><a href="#">Motivation</a></li>
                          <li><a href="#">PSD</a></li>
                          <li><a href="#">Responsive</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
  
{% endblock %}

blog/templates/blog/post_list.html
{% extends '_base.html' %}

<!-- Django filters -->
{% load i18n %}

<!-- Third party filters -->
{% load jalali_tags %}

<!-- My filters -->
{% load persian_translate_tags %}


{% block title %}

    {% trans 'post list'%}

{% endblock %}

{% block body %}

  <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                {% for post in posts %}
                  <div class="col-lg-6">
                    <div class="blog-post">
                      <div class="blog-thumb">
                        <a href="{{ post.get_absolute_url }}">
                          <img src="{{ post.image.url }}" alt="">
                        </a>
                      </div>
                      <div class="down-content">
                        <a href="{{ post.get_absolute_url }}">
                          <span>{{ post.title }}</span>
                        </a>
                        <ul class="post-info">
                          <li><a href="#">{{ post.author }}</a></li>
                          <li><a href="#">{{ post.published|to_jalali:'%Y %B %d'|number }}</a></li>
                          <li><a href="#">{{ post.comments.all|length }} {% trans "Comments" %}</a></li>
                        </ul>
                        <p>{{ post.content|truncatewords:10|safe }}</p>
                      </div>
                    </div>
                  </div>
                {% endfor %}
                <div class="col-12">
                  <nav aria-label="Page navigation example">
                      <ul class="pagination justify-content-center mt_3">
                          {% if page_obj.has_previous %}
                              <li class="page-item">
                                  <a class="page-link" href="?page={{ page_obj.previous_page_number}}">{% trans "Previous"%}</a>
                              </li>
                          {% endif %}
                          <li class="page-item">
                              <a class="page-link" href="#">1</a>
                          </li>
                          {% if page_obj.has_next %}
                              <li class="page-item">
                                  <a class="page-link" href="?page={{ page_obj.next_page_number}}">{% trans "Next"%}</a>
                              </li>
                          {% endif %}
                      </ul>
                  </nav>   
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </section>
  
{% endblock %}

pages/templates/pages/contact_us.html
contact us

templates/_base.html
<!-- Django Tags -->
{% load static %}
{% load i18n %}

<!-- My Tags -->
{% load category_tags %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">

        <!-- Bootstrap core CSS -->
        <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


        <!-- Additional CSS Files -->
        <link rel="stylesheet" href="{% static "assets/css/fontawesome.css" %}">
        <link rel="stylesheet" href="{% static "assets/css/templatemo-stand-blog.css" %}">
        <link rel="stylesheet" href="{% static "assets/css/owl.css" %}">
        
    </head>
    <body>

        <!-- This is a tag for load header.html with categories title in navbar -->
        {% categories_title %}

        {% comment %} 
        {% if messages %}
            <div class="container">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        {% endcomment %}

        {% block body %}
        
        {% endblock %}

        {% include "footer.html" %}

        <!-- Bootstrap core JavaScript -->
        <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
        <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

        <!-- Additional Scripts -->
        <script src="{% static "assets/js/custom.js" %}"></script>
        <script src="{% static "assets/js/owl.js" %}"></script>
        <script src="{% static "assets/js/slick.js" %}"></script>
        <script src="{% static "assets/js/isotope.js "%}"></script>
        <script src="{% static "assets/js/accordions.js" %}"></script>

        <script language = "text/Javascript"> 
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t){                   //declaring the array outside of the
        if(! cleared[t.id]){                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value='';         // with more chance of typos
            t.style.color='#fff';
            }
        }
        </script>

        <script src="" async defer></script>
    </body>
</html>

templates/footer.html
{% load i18n %}

<footer>
    <div class="container">
        <div class="row">
        <div class="col-lg-12">
            <ul class="social-icons">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Behance</a></li>
            <li><a href="#">Linkedin</a></li>
            <li><a href="#">Dribbble</a></li>
            </ul>
        </div>
        <div class="col-lg-12">
            <div class="copyright-text">
            <p>Copyright 2020 Stand Blog Co.
                    
                | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
        </div>
        </div>
    </div>
</footer>

templates/header.html
<!-- Django Tags -->
{% load i18n %}

<!-- My Tags -->
{% load category_tags %}

<!-- Header -->
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url "pages:home" %}"><h2>{% site_name %}<em>.</em></h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "pages:home" %}">
                        {% trans "Home"%}
                    </a>
                </li> 
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "blog:post_list" %}">
                        {% trans "Blog" %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">
                        {% trans "About Us" %}
                    </a>
                </li>
                {% for category in categories_info %}
                    <li class="nav-item">
                        {% comment %} <a class="nav-link" href="{% url "pages:contact_us" %}">{% trans "Contact Us" %}</a> {% endcomment %}
                        <a class="nav-link" href="{% url "blog:categories_post_list" category.slug %}">
                            {{ category.title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</nav>

templates/home.html
{% extends '_base.html' %}

<!-- Django filters -->
{% load i18n %}

<!-- Third party filters -->
{% load jalali_tags %}

<!-- My filters -->
{% load persian_translate_tags %}


{% block title %}

    {% trans 'home'%}

{% endblock %}

{% block body %}

  <section class="blog-posts">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">
              {% for post in posts %}
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{ post.image.url }}" alt="">
                    </div>
                    <div class="down-content">
                      <a href="{{ post.get_absolute_url }}"><h4><span>{{ post.title }}</span></h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ post.author }}</a></li>
                        <li><a href="#">{{ post.published|to_jalali:'%Y %B %d'|number }}</a></li>
                        <li><a href="#">{{ post.comments.all|length }} {% trans "Comments" %}</a></li>
                      </ul>
                      <p>
                        {{ post.content|safe }}
                      </p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for category in post.categories_Status_true.all %}
                                <li><a href="#">{{ category.title }}</a>,</li>
                              {% endfor %}                            
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}